% mrVolCutTools.m
% script
%
% Contains the gui controls for making cuts

cut_text = uicontrol(h_fig1,'Style','text','String','Create Cut',...
        'Units','normalized','Position',[.1 .63 .8 .05]);

setStartPointText = uicontrol(h_fig1,'Style','text',...
        'String','1. Select a start point for region to unfold.',...
        'Units','normalized','Position',[.1 .59 .8 .03],...
	'HorizontalAlign','left');
	  
setStartPointBtn = uicontrol(h_fig1,'Style','pushbutton',...
        'Interruptible','on',...
        'String','Set Start Point',...
	'Units','normalized','Position',[.3 .52 .4 .05],...
	'Callback',[...
	  'setVisiblesOff; set(previousBtn,''Visible'',''off''); set(nextBtn,''Visible'',''off'');,'...
	  'layer1Struct.selectedNode = -1;','grayStruct.selectedNode = -1;,'...
	  'displayStruct.flags(1) = -1; displayStruct.flags(2) = -1; displayStruct.flags(3) = 1;,'...
	  '[selectedNode,displayStruct.flags(3),imgStruct] = mrVolOverlayDist(volStruct,displayStruct,layer1Struct,selectedNode,cutNodes,mVoxelsStruct,h_fig2);,'...
	  'grayStruct.selectedNode = layer1Struct.selectedNode;',...
	  'if (layer1Struct.selectedNode == -1), displayStruct.flags(3) = -1; end,'...
	  'setVisiblesOn; set(previousBtn,''Visible'',''on''); set(nextBtn,''Visible'',''on'');']);

setCutPathText = uicontrol(h_fig1,'Style','text',...
        'String','2. Select points along which to cut.  The last point should be outside the unfold area.',...
        'Units','normalized','Position',[.1 .38 .8 .1],...
	'HorizontalAlign','left');
	  
setCutPathBtn = uicontrol(h_fig1,'Style','pushbutton',...
        'String','Select Cut Path',...
	'Units','normalized','Position',[.3 .35 .4 .05],...
	'Interruptible','on',...
	'Callback',[...
	  'setVisiblesOff;,'...
	  'if ~isempty(layer1Struct.dist),'...
	    'displayStruct.flags(1) = -1; displayStruct.flags(2) = -1; displayStruct.flags(4) = -1;,'...
	    '[selectedNode,displayStruct.flags(3),imgStruct] = mrVolOverlayDist(volStruct,displayStruct,layer1Struct,selectedNode,cutNodes,mVoxelsStruct,h_fig2);,'...
	    'isDone = 0;,'...
	    'selectedNodes = [];,'...
	    'while (isDone == 0),'...
	      'figure(h_fig2),'...
	      '[c r button] = ginput(1);,'...
	      'c = round(c); r = round(r);,'...
 	      '[nextNode, isDone] = addCutPathNode(c,r,button,displayStruct,layer1Struct,volStruct,h_fig2);,'...
	      'selectedNodes = [selectedNodes nextNode];,'...
	      '[selectedNode,displayStruct.flags(3),imgStruct] = mrVolOverlayDist(volStruct,displayStruct,layer1Struct,selectedNode,selectedNodes,mVoxelsStruct,h_fig2);,'...
	    'end,'...
	    '[displayStruct.flags(3), cutNodes] = mrVolSelectCut(selectedNodes,layer1Struct,volStruct);,'...
	    '[selectedNode,displayStruct.flags(3),imgStruct] = mrVolOverlayDist(volStruct,displayStruct,layer1Struct,selectedNode,cutNodes,mVoxelsStruct,h_fig2);,'...
	  'else,'...
	    'setVisiblesOn;',...
	    'disp(''ERROR: Unfold area not selected.  Please select a start point and try again.'');,'...
	  'end,'...
	  'setVisiblesOn;']);

saveCutText = uicontrol(h_fig1,'Style','text',...
        'String','3. Save the cut file in ''CutFile.mat''.',...
        'Units','normalized','Position',[.1 .26 .8 .05],...
	'HorizontalAlign','left');

saveCutBtn = uicontrol(h_fig1,'Style','pushbutton',...
        'String','Save Cut File',...
	'Units','normalized','Position',[.3 .21 .4 .05],...
	'Callback',[...
	    'changeDir(saveDir);,'...
	    'cmd = [''save '' grayF ''_cutFile cutNodes''];',...
	    'eval(cmd);',...
	    'changeDir(curDir);',...
	    'fprintf(''Cut saved in %s/%s\n'',saveDir,[anatomyF ''_cutFile'']);']);

separatorText = uicontrol(h_fig1,'Style','text',...
        'String','______________________',...
	'Units','normalized','Position',[.2 .14 .6 .05]);
    
clearCutBtn = uicontrol(h_fig1,'Style','pushbutton',...
        'String','Clear Cut',...
	'Units','normalized','Position',[.2 .08 .25 .05],...
	'Callback',[...
	  'mrVolClearCut;,'...
	  'mrVolChangeImageScript;']);

startOverBtn = uicontrol(h_fig1,'Style','pushbutton',...
        'String','Start Over',...
	'Units','normalized','Position',[.55 .08 .25 .05],...
	'Callback',[...
	  'mrVolStartOver;,'...
	  'mrVolChangeImageScript;']);

