% Script
% mrWindow2Controls
%
% 01.10.98 SJC
% PURPOSE:	Creates the guis for the main display window in mrUnfold
%
% MODIFICATIONS:
% 07.09.98 SJC	Adding tool to load and display data (color) at specific
%		gray matter locations.
% 07.13.99 SJC	Changed name from mrVolControls2 to mrWindows2Controls
% 	   SJC	Added tool to display loaded data from Show menu
%


set(h_fig2,'MenuBar','none');
set(h_fig2,'Name','mrUnfold Display',...
	'Units','Normalized',...
	'Position',[0.25 0.2 .75 .75]);
	
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%		FIGURE WINDOW 2			%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%% FILE MENU %%%%%%%%%%%%%%%%%%%%%%%

file_menu = uimenu(h_fig2,'Label','&File');

updateFlat_menu = uimenu(file_menu,'Label','&Update Flattened Display',...
	'Separator','on',...
	'Callback',['if ~exist(''h_fig3''), h_fig3 = figure;',...
		    'mrVolControls3;',...
		    '[flatStruct,flat] = mrVolReadFlat(1,flatStruct,flat,grayMatter,anatomy);',...
		    'end,',...
		    'mrVolShowFlat(flatStruct,mVoxelsStruct,grayStruct,cutNodes,h_fig3)']);
	   
save_menu = uimenu(file_menu,'Label','&Save Picture (TIFF)',...
		'Separator','on',...
		'Callback','mrVolTiffImage(imgStruct.dispImage,saveDir);');

quit_menu = uimenu(file_menu,'Label','&Quit mrVol',...
		'Separator','on',...
		'Callback','close all');

%%%%%%%%%%% SHOW GRAY/NODE/DIST %%%%%%%%%%%%%%%
show_menu = uimenu(h_fig2,'Label','&Show');

showGray_menu= uimenu(show_menu,'Label','&Gray', ...
    'Callback',...
    '[displayStruct.flags(2),imgStruct] = mrVolOverlayGray(volStruct,displayStruct,grayStruct.nodes(1:3,:),-1,cutNodes,mVoxelsStruct,h_fig2);');

showStartPoint_menu = uimenu(show_menu,'Label','&Start Point',...
    'Callback','mrShowStartPoint');

showDist_menu = uimenu(show_menu,'Label','&Distances', ...
    'Callback',['displayStruct.flags = [1 -1 -1 -1 -1];',...
    	'mrChangeImageScript;']);

showData_menu = uimenu(show_menu,'Label','&Loaded Data', ...
    'Callback', [...
		'if ~isempty(displayData),',...
		  'displayStruct.flags = [-1 -1 -1 -1 1];',...
		  'mrChangeImageScript;',...
		'else, errordlg(''No data loaded in.'');',...
		'end']);
    
showCut_menu = uimenu(show_menu,'Label','&Cut', ...
    'Callback','mrShowCut');

showMarks_menu = uimenu(show_menu,'Label','&Marked Voxels', ...
    'Callback',[...
    'displayStruct.flags = [-1 1 -1 1 -1];,'...
    'mrChangeImageScript;']);

%%%%%%%%%%% CLEAR GRAY/DIST/CUT %%%%%%%%%%%%%%%
clear_menu = uimenu(h_fig2,'Label','&Clear');

resetGray_menu = uimenu(clear_menu,'Label','&Gray',...
    'Callback', [...
	'mrClearGray;,'...
	'mrChangeImageScript;']);
	
resetNode_menu = uimenu(clear_menu,'Label','&Node',...
    'Callback', [...
	'mrClearStartPoint;,'...
	'mrChangeImageScript;']);

resetDist_menu = uimenu(clear_menu,'Label','&Dist',...
    'Callback', [...
	'mrClearDist;,'...
	'mrChangeImageScript;']);

resetCut_menu = uimenu(clear_menu,'Label','&Cut',...
    'Callback', [...
	'mrClearCut;,'...
	'mrChangeImageScript;']);

resetMarks_menu = uimenu(clear_menu,'Label','&Marked Voxels',...
    'Callback', [...
        'mrClearMarks;,'...
	'mrChangeImageScript;']);

resetAll_menu = uimenu(clear_menu,'Label','&All',...
    'Separator','on',...
    'Callback', [...
        'mrClearAll;,'...
	'mrChangeImageScript;']);

%%%%%%%%%%% SET NODE/RADIUS %%%%%%%%%%%
% Enter the node XYZ values by hand
set_menu = uimenu(h_fig2,'Label','Se&t');

pick_node_menu = uimenu(set_menu,'Label','&Start point for unfold', ...
    'Callback', [...
    '[selectedNode,imgStruct] = mrSelectStartPoint(volStruct,displayStruct,grayStruct.nodes,h_fig2);',...
    'set(Node_edit,''String'',num2str(selectedNode.index));',...
    'updated = ''idx'';',...
    'mrUpdateStartPoint;',...
    'mrChangeImageScript;']);

%%%%%%%%%%%%%%%%%% TOOLS %%%%%%%%%%%%%%%%%%%%

tools_menu = uimenu(h_fig2,'Label','&Tools');

unfold_menu = uimenu(tools_menu,'Label','&Unfold',...
	'Callback','mrUnfoldGUI');

cut_menu = uimenu(tools_menu,'Label','Create a &Cut',...
	'Callback','mrCreateCut');

area_menu = uimenu(tools_menu,'Label','&Mark Area',...
	'Callback','mrMarkArea');
	
dispdata_menu = uimenu(tools_menu,'Label','&Load and Display Data',...
	'Callback','mrDisplayData');

%%%%%%%%%%%%%%%%%% GRAPHICALLY SET PARAMETERS %%%%%%%%%%%%%%%

anatomyDir_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'Position',[10 740 200 15],...
	'HorizontalAlign','left',...
	'String','Directory for volume anatomy:');
anatomyDir_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'Position',[10 720 250 20],...
	'HorizontalAlign','left',...
	'String',anatomy.dir);
anatomyFile_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'Position',[10 700 100 15],...
	'HorizontalAlign','left',...
	'String','Volume anatomy file:');
anatomyFile_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'Position',[10 680 100 20],...
	'HorizontalAlign','left',...
	'String',anatomy.file);

loadAnatomy_btn = uicontrol(h_fig2,'Style','Pushbutton',...
	'String','Load Anatomy File',...
	'Position',[25 645 120 30],...
	'Callback',[...
	    'tempAnatomy.dir = get(anatomyDir_edit,''String'');',...
	    'tempAnatomy.file = get(anatomyFile_edit,''String'');',...
	    '[tempAnatomy,volStruct,displayStruct,grayStruct,layer1Struct,cutNodes] = mrVolReadVolume(tempAnatomy,volStruct,displayStruct,grayStruct,layer1Struct,cutNodes);,'...
	    'if ~isempty(tempAnatomy.dir),',...
	      'anatomy = tempAnatomy;',...
	      'grayMatter.hemisphere = []; grayMatter.file = [];',...
	      'set(grayHemisphere_edit,''String'',grayMatter.hemisphere);',...
	      'set(grayFile_edit,''String'',grayMatter.file);',...
	    'else, anatomy = tempAnatomy;',...
	      'set(anatomyDir_edit,''String'',anatomy.dir);',...
	      'set(anatomyFile_edit,''String'',anatomy.file);',...
	    'end,'...
	    'for ii = 1:3, set(iNumber_edit(ii),''String'',num2str(displayStruct.iNumber(ii)));	end,',...
	    'displayStruct.flags = [-1 -1 -1 -1 -1];',...
	    'mrChangeImageScript;']);

grayHemisphere_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'Position',[10 620 100 15],...
	'HorizontalAlign','left',...
	'String','Hemisphere:');
grayHemisphere_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'Position',[10 600 100 20],...
	'HorizontalAlign','left',...
	'String',grayMatter.hemisphere);
grayFile_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'Position',[10 580 100 15],...
	'HorizontalAlign','left',...
	'String','Gray matter file:');
grayFile_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'Position',[10 560 100 20],...
	'HorizontalAlign','left',...
	'String',grayMatter.file);

loadGray_btn = uicontrol(h_fig2,'Style','Pushbutton',...
	'String','Load Gray File',...
	'Position',[25 525 120 30],...
	'Callback',[...
	    'tempGrayMatter.hemisphere = get(grayHemisphere_edit,''String'');',...
	    'tempGrayMatter.file = get(grayFile_edit,''String'');',...
	    '[tempGrayMatter,grayStruct,layer1Struct] = mrVolReadGray(tempGrayMatter,grayStruct,layer1Struct,anatomy);,'...
	    'if isempty(tempGrayMatter),',...
	      'set(grayHemisphere_edit,''String'',grayMatter.hemisphere);',...
	      'set(grayFile_edit,''String'',grayMatter.file);',...
	    'else, grayMatter = tempGrayMatter;',...
	    'end,',...
	    'displayStruct.flags = [-1 1 -1 -1 -1];',...
	    'mrChangeImageScript;']);


radius_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'HorizontalAlign','left',...
	'FontSize',11,...
	'String','Radius (mm)',...
	'Units','points',...
	'Position',[10 300 80 15]);
radius_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'String',num2str(volStruct.radius),...
	'Units','points',...
	'Position',[80 300 30 15],...
	'Callback',['temp = str2num(get(radius_edit,''String''));',...
		'if (temp > 0), volStruct.radius = temp;',...
		'else, set(radius_edit,''String'',num2str(volStruct.radius));',...
		'end,',...
		'mrChangeImageScript;']);

startPt_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'FontSize',11,...
	'HorizontalAlign','left',...
	'String','Start Point',...
	'Units','points',...
	'Position',[10 255 40 28]);

S_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'HorizontalAlign','left',...
	'String','S',...
	'Units','points',...
	'Position',[60 270 12 15]);
S_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'String',num2str(selectedNode.S),...
	'Units','points',...
	'Position',[50 255 30 15],...
	'Callback',['updated = ''loc'';',...
		'mrUpdateStartPoint;']);

A_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'HorizontalAlign','left',...
	'String','A',...
	'Units','points',...
	'Position',[90 270 12 15]);
A_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'String',num2str(selectedNode.A),...
	'Units','points',...
	'Position',[80 255 30 15],...
	'Callback',['updated = ''loc'';',...
		'mrUpdateStartPoint;']);

C_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'HorizontalAlign','left',...
	'String','C',...
	'Units','points',...
	'Position',[120 270 12 15]);
C_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'String',num2str(selectedNode.C),...
	'Units','points',...
	'Position',[110 255 30 15],...
	'Callback',['updated = ''loc'';',...
		'mrUpdateStartPoint;']);

Node_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'HorizontalAlign','center',...
	'String','Node number',...
	'Units','points',...
	'Position',[60 235 70 15]);
Node_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'String',num2str(selectedNode.index),...
	'Units','points',...
	'Position',[70 220 50 15],...
	'Callback',['updated = ''idx'';',...
		'mrUpdateStartPoint;']);
		

saveDir_txt = uicontrol(h_fig2,'Style','text',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'Position',[10 30 200 15],...
	'HorizontalAlign','left',...
	'String','Save directory:');
saveDir_edit = uicontrol(h_fig2,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'Position',[10 10 250 20],...
	'HorizontalAlign','left',...
	'String',saveDir,...
	'Callback',[...
	    'tempDir = get(saveDir_edit,''String'');',...
	    'if (exist(tempDir,''dir'') == 7), saveDir = tempDir;',...
	    'else, set(saveDir_edit,''String'',saveDir); end']);
	
