% mrVolControls3.m

% set(h_fig3,'MenuBar','none');
set(h_fig3,'Name','mrVol Flattened Display',...
	'Units','Normalized',...
	'Position',[0.05 0.05 .3 .3]);


load_menu = uimenu(h_fig3,'Label','&Load');

loadFlat_menu = uimenu(load_menu,'Label','&Load Flattened Nodes',...
	'Callback',[...
	    '[flatStruct,flat] = mrVolReadFlat(1,flatStruct,flat,grayMatter,anatomy);',...
	    'mrVolShowFlat(flatStruct,mVoxelsStruct,grayStruct,cutNodes,h_fig3);']);

