% Script
% mrWindow1Controls
%

% Open new windows
% 
h_fig1 = figure;
h_fig2 = figure;

set(h_fig1,'MenuBar','none');
set(h_fig1,'Name','mrUnfold View Control',...
	'Units','Normalized',...
	'Position',[0.0101563 0.6875 0.224219 0.18457]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%		FIGURE WINDOW 1			%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
%%%%%%%%%%% PICTURE SETTINGS %%%%%%%%%%

pic_text = uicontrol(h_fig1,'Style','text','String','View Properties',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'FontSize',12,...
	'Units','points','Position',[26 139.5 207 18.9]);

%-------------- Contrast --------------	

max_text = uicontrol(h_fig1,'Style','text','String','Contrast Max',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'Units','points','Position',[138 105 45 24]);
	
slimax = uicontrol(h_fig1,'Style','slider', ...
    'Units','points', ...
    'Position',[185 106.8 51.3 19.8],...
    'Callback', 'mrVolChangeImageScript;');
set(slimax,'value',1);

min_text = uicontrol(h_fig1,'Style','text','String','Contrast Min',...
	'BackgroundColor',[0.8 0.8 0.8],...
	'Units','points','Position',[20 105 45 24]);
	
slimin = uicontrol(h_fig1,'Style','slider', ...
    'String','Min', ...
    'Units','points',...
    'Position',[65.7 106.8 52.2 19.8],...
    'Callback', 'mrVolChangeImageScript;');
set(slimin,'value',0);

%----------- Slice Orientation --------
sagittal_btn = uicontrol(h_fig1,'Style','RadioButton',...
	'String','Sagittal',...
	'Units','points','Position',[10 70 70 20],...
	'Value',1,...
	'Callback',[...
		'set(axial_btn,''Value'',0);',...
		'set(coronal_btn,''Value'',0);',...
		'displayStruct.activeSliceOri = 1;,'...
		'mrChangeImageScript;',...
                'set(gca,''DataAspectRatio'',[240/256,240/256,1.2]);']);

iNumber_edit(1) = uicontrol(h_fig1,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'String',num2str(displayStruct.iNumber(1)),...
	'Units','points','Position',[35 45 35 18],...
	'Callback',[...
		'displayStruct.iNumber(1) = str2num(get(iNumber_edit(1),''String''));,'...
		'mrChangeImageScript;']);

% Set sagittal as default view
displayStruct.activeSliceOri = 1;

axial_btn = uicontrol(h_fig1,'Style','RadioButton',...
	'String','Axial',...
	'Units','points','Position',[90 70 70 20],...
	'Callback',[...
		'set(sagittal_btn,''Value'',0);',...
		'set(coronal_btn,''Value'',0);',...
		'displayStruct.activeSliceOri = 2;,'...
		'mrChangeImageScript;',...
		'set(gca,''DataAspectRatio'',[240/256,1.2,240/256]);']);		

iNumber_edit(2) = uicontrol(h_fig1,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'String',num2str(displayStruct.iNumber(2)),...
	'Units','points','Position',[115 45 35 18],...
	'Callback',[...
		'displayStruct.iNumber(2) = str2num(get(iNumber_edit(2),''String''));,'...
		'mrChangeImageScript;']);

coronal_btn = uicontrol(h_fig1,'Style','RadioButton',...
	'String','Coronal',...
	'Units','points','Position',[170 70 70 20],...
	'Callback',[...
		'set(sagittal_btn,''Value'',0);',...
		'set(axial_btn,''Value'',0);',...
		'displayStruct.activeSliceOri = 3;,'...
		'mrChangeImageScript;',...
		'set(gca,''DataAspectRatio'',[240/256,1.2,240/256]);']);

iNumber_edit(3) = uicontrol(h_fig1,'Style','edit',...
	'BackgroundColor',[1 1 1],...
	'String',num2str(displayStruct.iNumber(3)),...
	'Units','points','Position',[195 45 35 18],...
	'Callback',[...
		'displayStruct.iNumber(3) = str2num(get(iNumber_edit(3),''String''));,'...
		'mrChangeImageScript;']);

%---------- Slice Selection -----------
previousBtn= ...
    uicontrol(h_fig1,'Style','pushbutton','String','<<  Prev', ...
    'Units','points',... 
    'Position',[55.8 8 54.9 24.4], ...
    'Callback', [...
       'step = -1;,'...
       'nImages = volStruct.vSize(displayStruct.activeSliceOri,3);,'...
       'displayStruct.iNumber(displayStruct.activeSliceOri) = mod(displayStruct.iNumber(displayStruct.activeSliceOri)-1+step,nImages) + 1;,'...
       'set(iNumber_edit(displayStruct.activeSliceOri),''String'',num2str(displayStruct.iNumber(displayStruct.activeSliceOri)));',...
       'mrChangeImageScript;']);

nextBtn= ...
    uicontrol(h_fig1,'Style','pushbutton','String','Next  >>', ...
    'Units','points',... 
    'Position',[144.9 8 54.9 24.4], ...
    'Callback', [...
       'step = 1;,'...
       'nImages = volStruct.vSize(displayStruct.activeSliceOri,3);,'...
       'displayStruct.iNumber(displayStruct.activeSliceOri) = mod(displayStruct.iNumber(displayStruct.activeSliceOri)-1+step,nImages) + 1;,'...
       'set(iNumber_edit(displayStruct.activeSliceOri),''String'',num2str(displayStruct.iNumber(displayStruct.activeSliceOri)));',...
       'mrChangeImageScript;']);

	

